[package]
name = "tauri-plugin-torchlight"
version = "0.1.0"
authors = ["mao <mao.lembryo@gmail.com>"]
description = "Tauri plugin for smartphone torchlight"
edition = "2021"
rust-version = "1.80.0"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-torchlight"

[dependencies]
tauri = { version = "2.0.0-rc.8" }
serde = "1.0.209"
thiserror = "1.0.63"

[build-dependencies]
tauri-plugin = { version = "2.0.0-rc.6", features = ["build"] }
