[package]
name = "tauri-plugin-torchlight-example"
version = "1.0.0"
description = "An example of using tauri-plugin-torchlight"
authors = ["mao lembryo@gmail.com"]
license = "MIT"
edition = "2021"
rust-version = "1.80.0"

[lib]
name = "tauri_plugin_torchlight_example"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.7", default-features = false, features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.8", features = [] }
tauri-plugin-torchlight = { path = "../../.." }
